version: '2'

services:

  ####################################
  #  LOGIC MODULE ON DC 1            #
  ####################################

  logicmodule1:
    image: "bscdataclay/logicmodule:trunk"
    ports:
      - "11034:11034"
    env_file:
      - ./env/LM.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro

  ####################################
  #  JAVA DATA SERVICES ON DC 1      #
  ####################################
  
  ds1java1:
    image: "bscdataclay/dsjava:trunk"
    depends_on:
      - logicmodule1
    ports:
      - 2127
    env_file:
      - ./env/DS.environment
      - ./env/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres1
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro

  ####################################
  #  PYTHON DATA SERVICES ON DC 1    #
  ####################################

  # Python ExecutionEnvironment (which, by default, are unused)
  # See initDC.sh shell script for more information on initialization
  ds1pythonee1:
    image: "bscdataclay/dspython:trunk-py2.7"
    depends_on:
      - ds1java1
    ports:
      - 6867
    env_file:
      - ./env/DS.environment
      - ./env/LM.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres1
      - DEBUG=false
      #- PYTHONVERBOSE=1

  #############################################
  #   LOGIC MODULE ON DC 2                    #
  #############################################
  
  logicmodule2:
    image: "bscdataclay/logicmodule:trunk"
    ports:
      - "12034:2034"
    env_file:
      - ./env/LM2.environment
    environment:
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - POSTGRES_HOST=lmpostgres2
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro

  ####################################
  #    JAVA DATA SERVICES ON DC 2    #
  ####################################

  ds1java2:
    image: "bscdataclay/dsjava:trunk"
    depends_on:
      - logicmodule2
    ports:
      - 2127
    env_file:
      - ./env/DS.environment
      - ./env/LM2.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres2
    volumes:
      - ./prop/global.properties:/usr/src/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/usr/src/dataclay/log4j2.xml:ro

  ####################################
  #  PYTHON DATA SERVICES ON DC 2    #
  ####################################

  # Python ExecutionEnvironment (which, by default, are unused)
  # See initDC.sh shell script for more information on initialization
  ds1pythonee2:
    image: "bscdataclay/dspython:trunk-py2.7"
    depends_on:
      - ds1java2
    ports:
      - 6867
    env_file:
      - ./env/DS.environment
      - ./env/LM2.environment
    environment:
      - DATASERVICE_NAME=DS1
      - POSTGRES_HOST=ds1postgres2
      - DEBUG=false
      #- PYTHONVERBOSE=1
