debug = false
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]


[web]
# Port for the status/dashboard page
address = ":8080"

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

   [entryPoints.https]
    address = ":443"
   [entryPoints.https.tls]
     # For secure connection on frontend.local
     [[entryPoints.https.tls.certificates]]
     certFile = "/ssl/frontend.cert"
     keyFile  = "/ssl/frontend.key"

[api]
